### ISSUE TITLE
Error setting up the yaml

### ISSUE THREAD

**Issue by JoeGandy** [landonr/homeThing#105]
**Describe the bug**
```
Failed config

binary_sensor.gpio: [source /config/.esphome/packages/c523de9d/common/ipod/lilygo_tdisplay_ipod_binary_sensor_pcf.yaml:17]
  
  Pin 0 incorrectly sets allow_other_uses: true.
  platform: gpio
  pin: 
    number: 0
    allow_other_uses: True
    inverted: True
```
Commenting line 
` common/ipod/lilygo_tdisplay_ipod_binary_sensor_pcf.yaml, # used for button controls` resolves the issue, but obviously breaks buttons
**To Reproduce**
1. Using default yaml: https://raw.githubusercontent.com/landonr/homeThing/main/tdisplay-s3.yaml

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by JoeGandy** [comment]
Potentially caused by https://github.com/landonr/homeThing/commit/416c33fd72800b0393d2b0d5d31eb39fc5a8230a

?

**Comment by landonr** [comment]
@JoeGandy I updated the yaml.

if you want to use the config locally use can do this. The file has to be available locally so you can copy it into your esphome folder
```yaml
packages: # maybe modify: include default ipod controls
  -+ ipod_control_binary_sensor_pcf: !include ../homeThing/common/ipod/lilygo_tdisplay_ipod_binary_sensor_pcf.yaml
  remote_package:
    url: https://github.com/landonr/homeThing
    ref: main
    files: [
      common/device_base.yaml, # defines api, ota, free memory and uptime sensor
      common/ipod/lilygo_tdisplay_ipod_battery.yaml, # used for battery percent
      # comment this out! common/ipod/lilygo_tdisplay_ipod_binary_sensor_pcf.yaml, # used for button controls
```
