### ISSUE TITLE
notifications

### ISSUE THREAD

**Issue by landonr** [landonr/homeThing#116]
**Is your feature request related to a problem? Please describe.**
notifications exist but theyre hard to call

**Describe the solution you'd like**
add service calls

**Additional context**
```yaml
voice_assistant:
  microphone: external_mic
  on_start:
    then:
      lambda: |-
        id(homeThingMenu)->clearNotifications();
        id(homeThingMenu)->addNotification("Voice Assistant", "Listening", "", true);
```

this should be a service call
