### ISSUE TITLE
Media player online image is not generated

### ISSUE THREAD

**Issue by iondulgheru** [landonr/homeThing#132]
Media player online image is not generated.
I added in HA the template sensor to create the sensor media_player_image_proxy_url. I also installed and configured imgproxy, I use it a docker container, I can't install it as an addon, as I use HA in docker, but it works properly anyway.
I think the problem is that this template should get the attribute entity_picture from a sensor called active_player.
No such sensor is defined in HA, I see that is defined in the HomeThing code, but is not exported to HA.
If I change the template to get this attribute from the the media_player I am using image generation works.
I think the active_player sensor should also be exposed to HA.
Or maybe i am doing something wrong?
I am using https://github.com/landonr/homeThing/blob/main/tdisplay-s3.yaml

**Comment by landonr** [comment]
youre right it's missing from the example code! I added it in #133, it's like this

```
homeassistant_media_player: # media player menu
  id: media_group_component
  finished_loading:
    id: media_players_loaded_sensor
  active_player: 
    id: active_player
    name: "${friendly_name} Active Player"
  media_players:
    - id: media_player_beam
      type: speaker
    - id: media_player_tv
      type: roku
```
