### ISSUE TITLE
m5 Stick Config Failing: "Unable to find action with the name 'homething_menu.scroll_counter_clockwise'."

### ISSUE THREAD

**Issue by barndawgie** [landonr/homeThing#136]
I'm trying to install homeThing to a brand new m5Stack FIRE device. When I try to validate the configuration in ESPHome Dashboard, I'm getting a failure: "Unable to find action with the name 'homething_menu.scroll_counter_clockwise'."

Here is my config, heavily based on your wiki and samples:

```yaml
---
substitutions:
  name: "home-thing"
  friendly_name: "homeThing"
  device_description: esp32 homeThing Remote Control
  board: m5stack-fire
  variant: esp32

packages:
  remote_package:
    url: https://github.com/landonr/homeThing
    ref: main
    files: [ # See https://github.com/landonr/homeThing/blob/main/GettingStarted.md
      common/device_base.yaml, # defines api, ota, free memory and uptime sensor
      common/m5stack-fire/backlight.yaml, # used for toggling backlight
      common/m5stack-fire/binary_sensor.yaml, # used for button controls
      common/m5stack-fire/binary_sensor_rotary.yaml, # used for rotary controls
      common/m5stack-fire/ip5306.yaml, # used for battery percent
      common/m5stack-fire/sidelight.yaml, # used to control LED strip
      common/fonts.yaml, # default font
      common/icon_fonts.yaml, # material icons
      common/images.yaml, # boot screen image
    ]
  base_config: !include config_deps/base_config.yaml

external_components:
  - source: # homeThing, display setup, and now playing app
      type: git
      url: https://github.com/landonr/homeThing
      ref: main
    refresh: 0s
    components: [
      homeThing, 
      homeThingDisplayState,
      homeThingApp, # only required if using apps
      homeThingAppNowPlaying # only required for Now Playing app
    ]
  - source:
      type: git
      url: https://github.com/landonr/esphome-components
      ref: main
    refresh: 0s
    components: [
      homeassistant_component,
      homeassistant_media_player,
      media_player_source,
      media_player_source_sonos,
      media_player_source_spotify,
      media_player_source_custom
    ]
  - source:
      type: git
      url: https://github.com/ssieb/custom_components
    components: [ ip5306 ]

esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  comment: ${device_description}

esp32:
  board: ${board}
  framework:
    type: esp-idf
  variant: ${variant}
```

Here is what I get from validate using ESPHome 2024.6.6 Dashboard:
```
INFO ESPHome 2024.6.6
INFO Reading configuration /config/home-thing.yaml...
INFO Updating https://github.com/landonr/homeThing@main
INFO Updating https://github.com/landonr/esphome-components@main
INFO Detected timezone 'America/Los_Angeles'
Failed config

binary_sensor.gpio: [source /config/.esphome/packages/c523de9d/common/m5stack-fire/binary_sensor.yaml:2]
  platform: gpio
  id: M5_BtnA
  pin: 
    number: 39
    inverted: True
  on_click: 
    then: 
      
      Unable to find action with the name 'homething_menu.scroll_counter_clockwise'.
      homething_menu.scroll_counter_clockwise: homeThingMenu
```

I don't _think_ this particular error can be caused by something on my side, but maybe I am missing something...
