### ISSUE TITLE
Make Homething node, display/subscribe to Home Assistant "notify.notify" service events .

### ISSUE THREAD

**Issue by ManuRiver** [landonr/homeThing#138]
This sparked the following idea and wanted to share back with you guys.

Add the following self published service to esphome config file. 

service:   ##provisions a self published service back to homeassistant thru esphome api.

```
api:
  encryption:
    key: !secret api

  services:
    - service: notify_homething
      variables:
        title: string
        message: string
        # type_str: string
      then:
        - lambda: |-
            id(homeThingMenu)->addNotification(title, message, "", true);
```

##configuration.yaml on the hass side, profit ;-) 

```
notify:
  - platform: group
    name: "Notify Homething"
    services:
      - service: esphome ##propagates the notify.notify events back to the variables and calls back the service.
        data:
          target: studiotdisplay_notify_homething
```

_Originally posted by @ManuRiver in https://github.com/landonr/homeThing/issues/116#issuecomment-2253511153_
