### ISSUE TITLE
add voice assist

### ISSUE THREAD

**Issue by landonr** [landonr/homeThing#46]
**Is your feature request related to a problem? Please describe.**
add a menu item to trigger voice assist

**Describe the solution you'd like**
the device needs to have a mic

like this https://www.youtube.com/embed/w6QxGdxVMJs

**Comment by landonr** [comment]
m5stickc has an issue with mic https://gitlab.com/geiseri/esphome_extras/-/issues/10
i cant get m5stack fire mic to work https://discord.com/channels/429907082951524364/1103409600780308510

i have a mic i can wire to a tdisplay so i'll try that

**Comment by xdecock** [comment]
Hi, i've managed to get the fire mic to work with those settings, however my m5 crash at the second pipeline start i can probably work that out, my issue with the m5 is with the speaker doing terrible sounds.

```yaml
#m5 fire
i2s_audio:
  i2s_lrclk_pin: GPIO13
  i2s_bclk_pin: GPIO12
  i2s_mclk_pin: GPIO0

microphone:
  - platform: i2s_audio
    id: adc_mic
    adc_type: internal
    adc_pin: GPIO34

# current craking speaker
speaker:
  - platform: i2s_audio
    dac_type: external
    i2s_dout_pin: GPIO25
    mode: mono

```
I'll try to make my m5stickc mic work and let you know
Bonus question what discord server is it?

**Comment by landonr** [comment]
this is the closest i got with the fire. It crashes for me after the second pipeline also. My audio sort of works. I was told to take out the automations from voice assistant and try that, but I haven't gotten around to it

```yaml
binary_sensor:
  - platform: gpio
    id: M5_BtnB
    pin:
      number: 38
      inverted: true
    on_multi_click:
      - timing:
          - ON FOR AT MOST 350ms
          - OFF FOR AT LEAST 10ms
        then:
          - media_player.toggle: media_player_out
      - timing:
          - ON FOR AT LEAST 350ms
        then:
          - voice_assistant.start:
      - timing:
          - ON FOR AT LEAST 350ms
          - OFF FOR AT LEAST 10ms
        then:
          - voice_assistant.stop:

spi:
  clk_pin: 18
  mosi_pin: 23
  miso_pin: 19

  i2s_audio:
    i2s_lrclk_pin: GPIO13
    i2s_bclk_pin: GPIO32
    i2s_mclk_pin: GPIO0
  
  microphone:
    - platform: i2s_audio
      adc_pin: GPIO34
      adc_type: internal
      id: adc_mic
  
  media_player:
    - platform: i2s_audio
      name: "${friendly_name} Internal Media Player"
      id: media_player_out
      dac_type: internal
      mode: right
  
  voice_assistant:
    microphone: adc_mic
    on_start:
      # - media_player.stop:
      #     id: media_player_out
      - light.turn_on:
          id: side_light
          blue: 100%
          red: 0%
          green: 0%
          effect: none
    on_tts_start:
      - light.turn_on:
          id: side_light
          blue: 60%
          red: 20%
          green: 20%
          effect: none
    on_tts_end:
      # - media_player.play_media:
      #     id: media_player_out
      #     media_url: !lambda return x;
      - light.turn_on:
          id: side_light
          blue: 60%
          red: 20%
          green: 20%
          effect: pulse
    on_end:
      # - delay: 1s
      # - wait_until:
      #     not:
      #       media_player.is_playing: media_player_out
      - light.turn_off: side_light
    on_error:
      - light.turn_on:
          id: side_light
          blue: 0%
          red: 100%
          green: 0%
          effect: none
      - delay: 1s
      - light.turn_off: side_light
```
