### ISSUE TITLE
Make 'Now Playing' an optional app

### ISSUE THREAD

**Issue by landonr** [landonr/homeThing#76]
**Is your feature request related to a problem? Please describe.**
Break out now playing into an optional app / screen

**Describe the solution you'd like**
make it included in the yaml like this
```yaml
homeThing:
  apps:
    - id: now_playing
    - id: pomodoro_timer
```

**Additional context**
this would let us add apps and games without complicating the existing component
